services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: testdb             
      MYSQL_USER: testUser               
      MYSQL_PASSWORD: testPassword       
    volumes:
      - ./sqlScripts/init_sql_server.sql:/docker-entrypoint-initdb.d/init_sql_server.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend_container
    image: node:20-slim  
    working_dir: /app
    volumes:
      - .:/app 
    ports:
      - "33333:33333"  
    environment:
      NODE_ENV: test 
      DB_HOST: db  
      DB_USER: testUser
      DB_PASSWORD: testPassword
      DB_NAME: testdb
    command: pnpm start:test 
    depends_on:
      db:
        condition: service_healthy  
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3"