name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root --password=rootPassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: rootPassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testUser
          MYSQL_PASSWORD: testPassword
        volumes:
          - ./sqlScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
          

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -P 3306 -u testUser -ptestPassword -e "SHOW DATABASES;" > /dev/null 2>&1; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Verify database initialization
        run: |
          mysql -h 127.0.0.1 -P 3306 -u testUser -ptestPassword -e "USE testdb; SHOW TABLES;"

      - name: Run ESLint
        run: pnpm eslint .

      - name: Run tests
        run: pnpm test
