name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose mysql-client

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build and start services
        run: docker-compose up -d

      - name: Run ESLint
        run: pnpm eslint .
        
      - name: Wait for MySQL to be ready
        run: |
          DB_HOST=localhost
          until mysqladmin ping -h"$DB_HOST" --silent; do
            echo "Waiting for MySQL..."
            sleep 1
          done
          echo "MySQL is ready!"
          
      - name: Run tests
        run: pnpm test

      - name: Stop services
        run: docker-compose down
